### PR TITLE
Changed: Move visibility in the details pane into the info box

### PR DESCRIPTION
**Pull request by joeferner**
- [x] @joeferner
- [x] @srfarley @kunklejr
- [x] @mwizeman @dsingley @EvanOxfeld 
- [x] @joeybrk372 @sfeng88 @rygim @jharwig 

This commit moves the visibility in the details pane for both
properties and comments from below the value to the popup info
box.

When using long visibility strings the details pane can become
cluttered quite fast. This addresses this by moving what most
users will not not typically use to get the job down into the
info box which is just one click away.

CHANGELOG
Changed: Move visibility in the details pane into the info box

### CODE REVIEW

**Comment by jharwig** [comment]
The visibility is to the right when there's enough space. For customers with shorter strings that would be preferred. Would rather have this as a config option if your project needs it

**Comment by dsingley** [comment]
I agree that it should be configurable

**Comment by jharwig** [comment]
Since visibility display is a extension point you could also show a short string and a hover div? Entirely in a plugin

**Comment by joeferner** [comment]
I just don't see how seeing visibility helps the analyst/investigator do their job, it only adds visual clutter. Modified date in my opinion is more useful so should it be visible as well?

**Comment by jharwig** [comment]
I think the cell level visibility is a core tenant of the product, it should be displayed by default. 

But, I could see use cases where customers wouldn't want it at all or a different piece of data there. So we should make it configurable to remove it and maybe even allow some other metadata there.

**Comment by kunklejr** [comment]
While I agree with @jharwig that cell visibility is a core tenant of the product, I do not think it should be shown on every field. It's a ton of noise on a display with lots of properties with long visibility strings. @jharwig and @dsingley, I think you'd change your opinion if you saw what Joe sees on his project. It's pretty ugly. I also agree with @joeferner that it doesn't really help the analyst. In fact, I'd say it probably hinders the analyst most of the time by distracting them from the data they really care about.

I suggest we move it under the "i" button with no configuration. Configuration implies multiple implementations, which I’d like to avoid as much as possible. It's just another permutation that will rarely, if ever, be tested.

**Comment by jharwig** [comment]
GW used the visibility and they were short. And that's the issue, we have to make things configurable. The maxim that you don't need options doesn't work for Visallo.

**Comment by jharwig** [comment]
the UI is already extremely customizable. But it has areas that aren't. Those should be made more configurable, not less.

**Comment by dsingley** [comment]
It may be ugly but I believe that it is a legal requirement. If the DO
wants to ignore it or get a waiver then Joe can hide it.

**Comment by jharwig** [comment]
This needs the new **visibility shown in properties list** configuration variable

**Comment by joeferner** [comment]
@jharwig done can you re-review

**Pull request merged**
