### PR TITLE
Upgrade vertexium to 2.5.2

### PR DESCRIPTION
**Pull request by jharwig**
- [x] @joeferner
- [x] @diegogrz
- [x] @mwizeman @sfeng88
- [x] @joeybrk372 @rygim @jharwig @EvanOxfeld

Testing Instructions: Umm, all of it? ;)

CHANGELOG
Changed: Upgrade Vertexium (2.5.2)

### CODE REVIEW

**Comment by jharwig** [comment]
Not sure if we should wait to merge until @joeferner pushes his migration script

**Comment by nidasid** [comment]
https://github.com/v5analytics/visallo-lts/issues/2220

**Comment by EvanOxfeld** [comment]
Should #2220 be resolved before merging?

**Comment by jharwig** [comment]
@EvanOxfeld  Not sure what to resolve, that exception looks like it's not using the new vertexium.

**Comment by EvanOxfeld** [comment]
Sounds good. If there's no issue here let's merge this PR.

**Pull request merged**
