### PR TITLE
Filter out string properties from histogram aggregation(2.1 cherry-pick)

### PR DESCRIPTION
**Pull request by joeybrk372**
- [x] @joeferner
- [ ] @srfarley @kunklejr
- [x] @mwizeman @dsingley @EvanOxfeld 
- [x] @joeybrk372 @sfeng88 @rygim @jharwig

### CODE REVIEW

**Comment by joeferner** [comment]
This PR looks to allow any field type. We can't histogram on any type. We can only histogram on dates and numbers.

**Comment by joeybrk372** [comment]
At @mwizeman 's suggestion, changed this pr to block strings. There are still some more types that don't fit into a histogram, but this will remove the majority of them. I think a more thorough solution for filtering aggregation properties would be better suited in a later release(possibly 2.2).

**Comment by jharwig** [comment]
Don't block all strings, zip codes are strings can be histogramed.

**Comment by jharwig** [comment]
@mwizeman  Can zip codes (which are strings) be histogramed? with the zip code boundary plugin

**Comment by dsingley** [comment]
zipcode boundaries are only used for choropleths,
https://en.wikipedia.org/wiki/Choropleth_map (not be confused
with geo-coordinate clusters)

**Comment by joeferner** [comment]
Based on https://www.elastic.co/guide/en/elasticsearch/reference/2.2/search-aggregations-bucket-histogram-aggregation.html and https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html histograms can only be applied to numeric or dates. Which makes sense. I think we handle zipcodes using a count aggregation.

**Comment by mwizeman** [comment]
@joeferner is correct on my previous experience with zip codes. We've always just used the count aggregation with those.

**Comment by jharwig** [comment]
@joeferner 
re: zip codes,
yeah counting is only what we do, thanks.

re: histogram versus couting,
I think you are right, we could combine the two into some better category. Not sure how best to implement that, whether it's client or server. Currently when count is selected and the buckets are too many (~250 maybe) we just punt. Is a count aggregation just a histogram with interval = 0?

**Comment by joeferner** [comment]
@jharwig I don't think so, they are two different ES calls. We could probably handle that in the back-end it's up to you.

The only problem I could I see with combining is what if you want to run counts on numbers. I guess setting the interval to 0 would work.

**Pull request merged**
