### PR TITLE
Setup JMX

### PR DESCRIPTION
**Pull request by rajanpardipuramv5**
- [x] @sfeng88 @rygim @jharwig 
- [x] @srfarley @rajanpardipuramv5 @joeferner

### CODE REVIEW

**Comment by sfeng88** [comment]
Why do we need this?

**Comment by srfarley** [comment]
@sfeng88 This is very helpful for seeing what's happening internally. We used it to look at session counts, etc. Jetty supplies MBeans, and so do some of our enterprise plugins. Use `jconsole` (included with the JDK) to connect to the local Jetty server.

**Comment by sfeng88** [comment]
So this is something we would only use locally not in a deployed environment?

**Comment by srfarley** [comment]
No, we used it in a deployed Tomcat also. But with Tomcat, you just supply system properties to enable JMX: https://tomcat.apache.org/tomcat-7.0-doc/monitoring.html#Enabling_JMX_Remote

**Comment by sfeng88** [comment]
How would we use this for a deployed jetty? We don't actually use this class when we deploy to Jetty.

**Comment by srfarley** [comment]
For Jetty, you set it up through configuration: http://www.eclipse.org/jetty/documentation/current/jmx-chapter.html

**Pull request merged**
