### PR TITLE
Add classes to export Element in RDF format

### PR DESCRIPTION
**Pull request by joeferner**
- [x] @sfeng88 @rygim @jharwig 
- [x] @srfarley
- [ ] @EvanOxfeld @joeybrk372
- [x] @mwizeman @dsingley

### CODE REVIEW

**Comment by srfarley** [comment]
Travis is reporting a valid test failure:
```
Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.08 sec <<< FAILURE! - in org.visallo.common.rdf.SetPropertyVisalloRdfTripleTest
testDateTimeValue(org.visallo.common.rdf.SetPropertyVisalloRdfTripleTest)  Time elapsed: 1.958 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...:pkey[B]> "2016-05-1[8T21:46:28-04:00]"^^<http://www.w3.or...> but was:<...:pkey[B]> "2016-05-1[9T01:46:28Z]"^^<http://www.w3.or...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.visallo.common.rdf.VisalloRdfTripleTestBase.assertEqualsVisalloRdfTriple(VisalloRdfTripleTestBase.java:13)
	at org.visallo.common.rdf.SetPropertyVisalloRdfTripleTest.testValue(SetPropertyVisalloRdfTripleTest.java:89)
	at org.visallo.common.rdf.SetPropertyVisalloRdfTripleTest.testValue(SetPropertyVisalloRdfTripleTest.java:78)
	at org.visallo.common.rdf.SetPropertyVisalloRdfTripleTest.testDateTimeValue(SetPropertyVisalloRdfTripleTest.java:64)
```
```

**Comment by joeferner** [comment]
Timezone issue, I'll need to take a look

**Comment by joeferner** [comment]
@srfarley Should be fixed but Travis decided not to build this branch

**Comment by srfarley** [comment]
@joeferner I manually rebuilt and it passes now: https://travis-ci.org/v5analytics/visallo/builds/131497669

**Pull request merged**
