### PR TITLE
Allow alert.ejs to display html content. Also fix scoping of alert.ejs variables

### PR DESCRIPTION
**Pull request by joeferner**
- [ ] @sfeng88 @rygim @jharwig 
- [x] @srfarley @joeferner
- [x] @EvanOxfeld @joeybrk372
- [ ] @mwizeman @dsingley

So it turns out that `alert.ejs` was leaking the `info` variable. I wrapped this template in a `function`.

### CODE REVIEW

**Comment by jharwig** [comment]
I'd be worried about displaying user generated content in the alert causing xss vulnerabilities...

**Comment by jharwig** [comment]
and this is starting to have too much logic, it should be a component

**Comment by joeferner** [comment]
@jharwig That's why I made it very explicit. You have to pass `errorHtml`, `infoHtml`, or `messageHtml` instead of `error`, `info`, or `message`

**Comment by joeferner** [comment]
@jharwig also agreed about the component aspect but I didn't really want to change it in the 13 other places it's used.

**Comment by jharwig** [comment]
re: okay okay, I see

You wouldn't need to change all of them initially, leave the ejs file (since the component would use hbs) and add a deprecation console warning inside the template.

It would also allow behavior in the alert panel. Like expandable more info

**Comment by joeferner** [comment]
@jharwig For now can we just live with the changes. I think a component is the right move but it's probably not a Flight component but a React component. Can we make that change after the current release.

**Pull request merged**
