### PR TITLE
Fix select connected (ctrl-e) to use more reliable way to get edges.

### PR DESCRIPTION
**Pull request by jharwig**
- [x] @sfeng88 @rygim @jharwig 
- [x] @srfarley @joeferner
- [x] @EvanOxfeld @joeybrk372
- [x] @mwizeman @dsingley

Also introduce a slight delay in the case the user clicks and uses key combo immediately

Adds some info popups that show what is happening

### CODE REVIEW

**Comment by EvanOxfeld** [comment]
Looks good. `this.onSelectConnected` is starting to grow -- consider raising the level of abstraction and reducing the promise nesting, which is always easier to read.

Also, what's the source of the delay -- is it due to passing messages between workers and the main thread or is it due to fetching vertices and edges? If it's the latter, is the timeout enough in the case of  a high latency / low bandwidth connection?

**Comment by jharwig** [comment]
@EvanOxfeld The delay is to compensate between the time the graph notices the click and triggers an event that propagates to the document. There is delay built into the graph because of the way we have to coalesce selection changes (cytoscape sends them one at a time – select 10 things, get 10 events) Into one selection change event. It's not based on any network latency, only the built in graph delay (`SELECTION_THROTTLE` in graph.js) and the bubbling delay (which might be synchronous anyways)

Now I could make that a constant to ensure they stay in sync

**Comment by EvanOxfeld** [comment]
A constant sounds good. And thanks for the helpful explanation -- makes more sense now.

**Comment by jharwig** [comment]
@EvanOxfeld done

**Pull request merged**
