### PR TITLE
Changed: Moved threading logic for GPW/LRP from initializers to runners

### PR DESCRIPTION
**Pull request by joeferner**
- [x] @joeferner
- [ ] @kunklejr
- [ ] @mwizeman @dsingley @EvanOxfeld 
- [x] @joeybrk372 @sfeng88 @rygim @jharwig 

By moving the logic of starting threads from the initializer to the runner
we are able to make standalone applications which start GPW and LRP processing
threads.

CHANGELOG
Changed: Moved threading logic for GPW/LRP from initializers to runners. Allows for making standalone application which start GPW and LRP processing threads.

### CODE REVIEW

**Comment by sfeng88** [comment]
@joeferner in the changelog entry, can we add a little bit more detail please? I would be ok with using the commit message.

**Comment by joeferner** [comment]
@sfeng88 How is that?

**Comment by mwizeman** [comment]
Should ExternalResourceRunner be refactored to work like this too? Conceptually it seems like a pretty similar task to these refactored versions.

**Comment by joeferner** [comment]
@mwizeman `ExternalResourceRunner` was already in core and didn't have dependencies on web. It also works a little differently.

**Pull request merged**
