### PR TITLE
Work product migration

### PR DESCRIPTION
**Pull request by jharwig**
- [ ] @joeferner
- [ ] @kunklejr @mwizeman @sfeng88 @diegogrz
- [ ] @dsingley @EvanOxfeld 
- [x] @joeybrk372 @rygim @jharwig 

Save for after 3.0, as it forces migration to have run before server will start

CHANGELOG
Added: Migration script to transition from workspace entity to graph work product

### CODE REVIEW

**Comment by rygim** [comment]
enterprise + workgroup have both been tested with this PR and they both work.

**Comment by jharwig** [comment]
Remember to cherry pick to master after merge

**Comment by rygim** [comment]
@jharwig created PR against master: https://github.com/v5analytics/visallo/pull/746

**Comment by EvanOxfeld** [comment]
Merging so @nidasid can start testing.

**Pull request merged**
