### PR TITLE
Changed: Cytoscape.js force directed layout from arbor to cose

### PR DESCRIPTION
**Pull request by joeferner**
- [x] @joeferner
- [x] @kunklejr @mwizeman @sfeng88 @diegogrz
- [ ] @dsingley @EvanOxfeld 
- [ ] @joeybrk372 @rygim @jharwig 

According to https://github.com/cytoscape/cytoscape.js-arbor arbor is
not recommened in favor of cose, cose-bilkent, or cola. After trying
them I found cose to be the best for speed and layout balance. bilkent
was quite slow even on my machine. cola didn't offer much above cose.
I choose cose because it is now part of cytoscape which means one
less dependency and compatibility should remain high.

CHANGELOG
Changed: Cytoscape.js force directed layout from arbor to cose

### CODE REVIEW

**Comment by jharwig** [comment]
Please no PRs for graph/map as they are new components in 3.0.

I will incorporate these changes in work-products branch

**Comment by rygim** [comment]
What should we do with this PR? @joeferner can we close it or do you need it? @jharwig did you integrate it into your work product branch?

**Comment by joeferner** [comment]
We can close this if @jharwig says he's good and integrated in his branch

**Comment by jharwig** [comment]
Yup, it's in 3.0 to use cose by default

**Pull request closed without merging**
