### PR TITLE
Fix bug with rendering edge comments, and factor out common code between vertex and edge set property routes into a helper class

### PR DESCRIPTION
**Pull request by srfarley**
- [x] @joeferner
- [x] @mwizeman @dsingley @EvanOxfeld 
- [x] @joeybrk372 @sfeng88 @rygim @jharwig 

The comment key is now consistent (a timestamp) between vertices and edges.

### CODE REVIEW

**Comment by joeferner** [comment]
Is there a big enough difference between Vertex and Edge that they couldn't just be subclasses of a `SetPropertyRouteBase` class?

**Comment by srfarley** [comment]
There are enough differences where the base class would be the same as `SetPropertyRouteHelper` with protected instead of public methods. It doesn't matter to me either way.

**Comment by joeferner** [comment]
I was just guessing that they should be a lot more similar and if they aren't why not. Why is an edge different from a vertex?

**Comment by srfarley** [comment]
`VertexSetProperty` accepts multiple property values, has special logic for dependent properties, and saves multiple results which are returned as JSON. `EdgeSetProperty` broadcasts an workspace updates for its vertices, while `VertexSetProperty` broadcasts only itself. The `handle()` methods are quite different between the two.

**Comment by jharwig** [comment]
Shouldn't edges handle dependent properties too?

**Comment by srfarley** [comment]
I suppose they should. I guess we've never had the need.

**Comment by srfarley** [comment]
I switched to using a base class for the routes so we can migrate towards common functionality.

**Pull request merged**
