### PR TITLE
Fix multipart configuration and error handling

### PR DESCRIPTION
**Pull request by jharwig**
- [x] @joeferner
- [ ] @diegogrz
- [x] @mwizeman @sfeng88
- [x] @joeybrk372 @rygim @jharwig @EvanOxfeld

* Remove jetty specific handling of multipart requests in favor of servlet 3 api spec
* Add configuration parameters to adjust upload limits

    ```
    multipart.location, multipart.maxFileSize, multipart.maxRequestSize, multiPart.fileSizeThreshold
    ```
* Make sure error messages get propagated to client correctly
* Tested in Jetty, and Tomcat

Testing Instructions:
Upload files that pass/fail the file upload size checks. Per file limit is 10MB by default, total upload limit is 50MB (choose 6 files slightly less than 10MB each to fail this)

Points of Regression: None

CHANGELOG
Added: Configuration parameters to adjust the web server file upload limits. Set to 10MB / file, and 50MB / upload by default. `multipart.maxFileSize` and `multipart.maxRequestSize`
Fixed: Error message correctly displays for uploads exceeding size limits

### CODE REVIEW

**Comment by jharwig** [comment]
Will Cherry-pick to master after review

**Comment by jharwig** [comment]
Suggestions on the default limits welcome...  is 10MB enough?

**Comment by EvanOxfeld** [comment]
10MB seems on the small size. A large PDF or a zip file could easily be larger. What's the downside to bumping up the limit?

**Comment by jharwig** [comment]
just DOS attacks and system resources. What should they be by default?

**Comment by jharwig** [comment]
upped the limits to 50MB max per file and 100MB max per bulk upload

**Pull request merged**
