### PR TITLE
Refactor: Move logic from UserPropertyAuthorizationRepository to a base class

### PR DESCRIPTION
**Pull request by joeferner**
- [x] @joeferner
- [x] @srfarley @kunklejr
- [x] @mwizeman @dsingley @EvanOxfeld 
- [x] @joeybrk372 @sfeng88 @rygim @jharwig 

This refactor will ease the implementation of non-updateable auth repos

### CODE REVIEW

**Comment by srfarley** [comment]
How about a couple of unit tests?

**Comment by joeferner** [comment]
@srfarley We already have a unit test for `UserPropertyAuthorizationRepositoryTest` which still passes. The primary change here is to help other project proprietary authorization repositories by providing a base class which does not allow updating through a public API.

**Comment by srfarley** [comment]
@joeferner :+1:

**Comment by sfeng88** [comment]
@joeferner won't this change break people who are running on a released version?

**Pull request merged**
