### PR TITLE
remove includes as IE doesn't have it

### PR DESCRIPTION
**Pull request by jharwig**
- [x] @srfarley @joeferner
- [x] @mwizeman @dsingley @EvanOxfeld 
- [x] @joeybrk372 @sfeng88 @rygim @jharwig

### CODE REVIEW

**Comment by EvanOxfeld** [comment]
`Array.prototype.includes` should be available via `babel-polyfill`. Perhaps the polyfill needs to be served up by requirejs?

**Comment by jharwig** [comment]
this isn't using babel yet

**Comment by EvanOxfeld** [comment]
How is `UserAdminPrivilegesPlugin.jsx` transpiled? That being said, I wouldn't want to hold up this PR.

**Comment by joeferner** [comment]
@EvanOxfeld using `org.visallo.web.WebApp#registerJavaScriptComponent` which will use babble to compile the jsx to js

**Comment by jharwig** [comment]
@EvanOxfeld @joeferner okay, my mistake. I'll create an issue to follow up.

**Pull request merged**
